### PR TITLE
No sudo on Debian + typofix

### PR DESCRIPTION
**Pull request by v-p-b**

### CODE REVIEW

**Comment by tklengyel** [comment]
You don't need sudo for apt?

**Comment by v-p-b** [comment]
Debian doesn't install sudo by default (this is the target guest VM, right?), I indicated the need for root by the hash prefix.

**Comment by tklengyel** [comment]
> this is the target guest VM, right

Yes

> I indicated the need for root by the hash prefix.

I think that's less obvious then with `sudo`. Perhaps `su -` before the apt line would be better.

**Comment by tklengyel** [comment]
There was an additional spot in the README that needed fixing so I just fixed all in one swoop. Thanks for the PR though!

**Pull request closed without merging**
